import { Injectable } from '@angular/core'

@Injectable()
export class PodcastService {
    getPodcasts() {
        return PODCASTS
    }

    getPodcast(id:number) {
        return PODCASTS.find(podcast => podcast.id === id)
    }
}

const PODCASTS = [
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast31.jpg?alt=media&token=5b0e728f-4a21-4490-8b18-f9ae04ae785d",
        duration : "1hr",
        id : 31,
        playerSrc: 'https://app.hearthis.at/embed/5131881/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "18 August 2020",
        releaseInfoP1 : "This marks the 12th show on Fnoob Techno Radio, and of course podcast number 31 in the series.",
        releaseInfoP2: "For this set I stepped away from the digital realm of Serato and picked out a load of banging techno records.",
        style : "Hard Techno",
        shortDescription: '1 hour of hard banging techno. Tracks by the likes of Mike Humphries, W.J Henze, DJ Mika, Patrick DSP, Dirty Bass & Kay D Smith.',
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast31.jpg?alt=media&token=965c65c2-4810-4773-9b8f-4fd56eeb26ce",
        title : "GTA Digital Podcast #31",
        tracksBy : "Mike Humphries, W.J Henze, DJ Mika, Patrick DSP, Dirty Bass & Kay D Smith to name just a few. Some real bangers that I picked up over the years before jumping ship and using Serato."
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast30.jpg?alt=media&token=98e02124-5b2e-4367-b9cb-a4e4bca173d9",
        duration : "1hr",
        id : 30,
        playerSrc: 'https://app.hearthis.at/embed/5049644/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "18 August 2020",
        releaseInfoP1 : "The GTA Digital Podcast is back with the 30th installment. As always you can expect an hour of straight up, straight forward, hard banging techno.",
        style : "Hard Techno",
        shortDescription: '1 hour of hard banging techno. Tracks by the likes of The Divide, DJ Mike, Vincent de Wit, DJ Ogi, Lars Klein & The Anxious.',
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast30.jpg?alt=media&token=72b88875-4969-43a8-9b94-f26e2341ce25",
        title : "GTA Digital Podcast #30",
        track1 : "23 Terawatts (Original Mix) - The Divide",
        track10 : "Smoke This (Original Mix) - DJ Mika",
        track11 : "Renascent (Original Mix) - A. Johansson & M. Fridell",
        track12 : "Illegal Intentions (Original Mix) - Primal",
        track13 : "Ogre Hands (Original Mix) - David Moleon",
        track14 : "Grande Fiesta (Original Mix) - DJ Mika",
        track15 : "Subrepress (Original Mix) - Vincent de Wit",
        track16 : "Garaza (Original Mix) - DJ Ogi",
        track17 : "Full Charge (Original Mix) - Vincent de Wit",
        track18 : "Prodrive (Ben Long Remix) - Mike Humphries",
        track19 : "Polar Magnetism (Original Mix) - Concrete Djz",
        track2 : "Malfunction (Original Mix) - Mattias Fridell",
        track20 : "Atomska (Original Mix) - DJ Ogi & Concrete Djz",
        track21 : "Proc (Original Mix) - DJ Ogi",
        track22 : "Darkness In Yer Eyes (Original Mix) - Weichentechnikk & Marcel Cousteau",
        track3 : "Music (Original Mix) - Lars Klein",
        track4 : "Tengu (Original Mix) - Concrete Djz",
        track5 : "Sidetude (Original Mix) - Primus Tech",
        track6 : "Inform (Original Mix) - Andre Walter & Chris Hope",
        track7 : "Sixfold Symmetry (Original Mix) - The Anxious",
        track8 : "Darko Barko (Bas Mooy & Vincent de Wit Remix) - Olivier Giacomotto",
        track9 : "Reconstruction (Original Mix) - Concrete Djz",
        tracksBy : "The Divide, Mattias Fridell, Lars Klein, Vincent de Wit, Bas Mooy & The Anxious."
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast29.jpg?alt=media&token=ed2fe895-8d77-4e8c-91ca-156d9901a449",
        duration : "1hr",
        id : 29,
        playerSrc: 'https://app.hearthis.at/embed/4970726/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "18 August 2020",
        releaseInfoP1 : "For this podcast I put together an hour set using tracks released on Armatura Clandestine. Some real solid, seriously banging hard techno.",
        style : "Hard Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast29.jpg?alt=media&token=ef605108-d665-4268-a665-425ce6d34fa7",
        title : "GTA Digital Podcast #29",
        track1 : "Estetika Stroja - Luka Baumann",
        track10 : "Father - Wetworks",
        track11 : "Ton Theos - Tuomas Rantanen",
        track12 : "Category 5 - The Divide",
        track13 : "Fade Into Darkness - Brad Lee",
        track14 : "Laughing Pain - Broken Rules",
        track15 : "Big Bang! - Concrete Djz",
        track16 : "Beat Factory - Ganez The Terrible",
        track17 : "Nano Surgery - Mattias Fridell",
        track18 : "Borgata - Primal",
        track19 : "Downgoing Plates - Tuomas Rantanen",
        track2 : "Scroll Lock - Concrete Djz",
        track20 : "Blueprint To Revenge - Wetworks",
        track21 : "Night & Day - Wetworks",
        track22 : "Lady Of The Night - Zeitgeist",
        track23 : "Draconian - Toumas Rantanen",
        track3 : "In Your Mind - The Divide",
        track4 : "Maan - Tuomas Rantanen",
        track5 : "Pedala - Concrete Djz",
        track6 : "Sheep Killer - Ian Lehman",
        track7 : "Force Direction - Mattias Fridell",
        track8 : "Causality - Tuomas Rantanen",
        track9 : "Heavy Limbs - Concrete Djz",
        tracksBy : "The Divide, Mattias Fridell, Lars Klein, Vincent de Wit, Bas Mooy & The Anxious."
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast28.jpg?alt=media&token=6e7a4be2-b087-4ce0-9146-8756a8103bda",
        duration : "1hr",
        id : 28,
        playerSrc: 'https://app.hearthis.at/embed/4888136/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "24 June 2020",
        releaseInfoP1 : "Another month gone by, which meant another installment of GTA Digital Presents on Fnoob Techno Radio, and therefore another mix to add to the podcast series.",
        releaseInfoP2 : "This month I decided to get back to it after two banging guests. I've recently been looking for some older style hard, driving, percussive techno, but with some groove to it. After hours of searching I managed to find loads of tracks in the style I was after, and in this mix you'll hear just a small portion of what I found.",
        style : "Hard Groove/Tough Tribal Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast28.jpg?alt=media&token=3bfb36e9-66b0-4d03-88a4-1accc80ebfae",
        title : "GTA Digital Podcast #28",
        track1 : "Very Disco (Original Mix) - Rydel",
        track10 : "Infame (David Moleon New Mix) - Primus V",
        track11 : "Marconni (Original Mix) - Primus Tech",
        track12 : "Comprimeme (Original Mix) - Iago De La Vega & David Moleon",
        track13 : "Samaha (Original Mix) - Dito Masats",
        track14 : "Car Crash (Original Mix) - Primus V",
        track15 : "Porlapolla (Original Mix) - David Moleon & Audiowarp",
        track16 : "Violence Makes Violence (Original Mix) - Odessa SoundFreaks",
        track17 : "Nipples from Outerspace (Original Mix) - Lars Klein",
        track18 : "Darko Barko (Original Mix) - Olivier Giacomotto",
        track19 : "Nobody Freaks Like Us (Original Mix) - Rowlanz",
        track2 : "Mokada (Original Mix) - Victor Martin",
        track20 : "Bushido (Original Mix) - Vincent de Wit & Bas Mooy",
        track3 : "Beauty Life (Original Mix) - Iago De La Vega",
        track4 : "Form 1 (Original Mix) - Primus V",
        track5 : "Ready Or Not (David Moleon Remix) - Odessa SoundFreaks",
        track6 : "Rebecca (Original Mix) - Ganez",
        track7 : "Dropping Device (Original Mix) - Lars Klein",
        track8 : "Two Midgets (Original Mix) - DJ Link",
        track9 : "Buenaverde (Original Mix) - Dito Masats",
        tracksBy : "Rydel, Victor Martin, Ganez, DJ Link, Primus V & David Moleon"
    },
    {
        artistName : "Kyle Horne",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast27.jpg?alt=media&token=d2d95fec-77ec-4d4c-9693-1287cac47641",
        duration : "1hr",
        id : 27,
        playerSrc: 'https://app.hearthis.at/embed/4791898/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "27 May 2020",
        releaseInfoP1 : " The GTA Digital Podcast is back after an absolutely banging 8th installment of the GTA Digital Presents show on Fnoob Techno Radio. This month saw Kyle Horne lay down some serious bangers.",
        releaseInfoP2 : "Kyle is a Scottish Techno DJ who has played at various events and free parties across the country, and is a resident at Glasgow based Acid Techno night, Squelch, and also part of the 6tms Anon and Taikosound Sound Systems, where you can see him hammering out the goodies.",
        releaseInfoP3 : "Kyle focuses on the harder side of techno, with his all vinyl sets ranging from straight up techno, as you'll hear in this set, to Acid Techno, Tekno & Acidcore.",
        style : "Techno/Hard Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast27.jpg?alt=media&token=f009059b-e127-4469-97f3-d66cf109920f",
        title : "GTA Digital Podcast #27"
    },
    {
        artistName : "Bushby",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast26.jpg?alt=media&token=a9d5579c-58f2-4b26-a8e8-e477f25b717d",
        duration : "1hr",
        id : 26,
        playerSrc: 'https://app.hearthis.at/embed/4672202/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "2 May 2020",
        releaseInfoP1 : "The GTA Digital Podcast is back, following this months show on Fnoob Techno Radio, which saw Leeds(UK) based DJ, Bushby, take the reins, laying down an hour of some excellent techno. Starting off with something a bit more breaky, but soon into the straight up bangers.",
        style : "Straight Up/Hypnotic Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast26.jpg?alt=media&token=4cbccd4e-5fb1-40bc-97db-328b6538abac",
        title : "GTA Digital Podcast #26",
        track1 : "Palekh - Jungle Calling (Original Mix) ",
        track10 : "Cassegrain - First Words (Original Mix)",
        track11 : "Mall Grab - Hidden Worlds (Rave Mix)",
        track12 : "Less Instructions - Upload Your Mask (Original Mix)",
        track13 : "Chris Moss Acid - Machine Heavy (Original Mix)",
        track14 : "Signum - What Ya Got For Me (JoeFarr Re-edit)",
        track2 : "Fear-E - Puro (Original Mix) ",
        track3 : "Lukes Anger ft. Death of Death of Discoteque - When Will You Take (Original Mix)",
        track4 : "Carpainter - Shock Out (Original Mix)",
        track5 : "Dave Mono - All Aboard (Original Mix)",
        track6 : "DJ Boss - Zaba (Original Mix)",
        track7 : "Diabla Diezco - LSD TV (Original Mix)",
        track8 : "Asquith - Gang (Original Mix)",
        track9 : "Viers - Four (Original Mix)",
        tracksBy : "Chris Moss Acid, Dave Mono, DJ Boss, Palekh & Fear-E"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast25.jpg?alt=media&token=17414edb-6d75-4f2d-b304-5edd635269ff",
        duration : "1hr",
        id : 25,
        playerSrc: 'https://app.hearthis.at/embed/4561994/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "10 April 2020",
        releaseInfoP1 : "The GTA Digital Podcast is back, with myself, Gary The Apprentice, laying down some techno for ya'll. This time something a bit different, and something that I've never done before. For this show I've decided to put a set together in Ableton, with over 40 tracks spread out across 4 channels, and performed using a Novation Launchpad and Launchcontrol XL.",
        releaseInfoP2 : "Expect an hour of absolutely banging techno, with 4 tracks constantly in the mix for the majority of the set.",
        style : "Hard Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast25.jpg?alt=media&token=cbf00865-5cd1-4929-a31f-a2a84a1cab5b",
        title : "GTA Digital Podcast #25",
        track1 : "Surgeon - Depart (Original Mix)",
        track10 : "Gary The Apprentice - Illusions of Reality (Original Mix)",
        track11 : "Wetworks vs V.I.T.R.I.O.L. - Subdue Your Passions (Original Mix)",
        track12 : "Dave Mono - Thuns (Original Mix)",
        track13 : "Ollie Linear - You're Forcing Me (Feat' Melissa) (Original Mix)",
        track14 : "Lars Klein - Sweat pt. 2 (Original Mix)",
        track15 : "DJ Ogi - Kaotik (Original Mix)",
        track16 : "Jeff Mills - The Bells (Original Mix)",
        track17 : "Mike Wade - Death Rattle Drum (Original Mix)",
        track18 : "Lars Klein - Black Rain (Original Mix)",
        track19 : "The Anxious - Stalker (Original Mix)",
        track2 : "The Anxious, Brainshaker - Draw Out Your Breeches (Original Mix)",
        track20 : "Patrick DSP - Scum Like You (Original Mix)",
        track21 : "Audioklinik - Critical Path (Original Mix)",
        track22 : "Peter B - Pitbull (Original Mix)",
        track23 : "Primal - Borgata (Original Mix)",
        track24 : "Ryuji Takeuchi - Ichigo Ichie (Original Mix)",
        track25 : "DJ Bam Bam & Jamie Bissmire - Bad Boy Bass (Original Mix)",
        track26 : "Audioklinik - Polyphem (Original Mix)",
        track27 : "Bradlee - Intended Harm (Original Mix)",
        track28 : "Broken Rules - Laughing Pain (Original Mix)",
        track29 : "DJ Ogi - Hartera (Original Mix)",
        track3 : "The Anxious - Begin To Understand (Original Mix)",
        track30 : "Dj Boss - No Room To Move (Original Mix)",
        track31 : "DJ Pauze & Patrick DSP - Disgraceful Scene (Original Mix)",
        track32 : "Ignition Technician - Shark Attack (Glenn Wilson Remix)",
        track33 : "Dean Rodell - Part of A Complication (Original Mix)",
        track34 : "Wetworks - Explanations Are Useless (Original Mix)",
        track35 : "Jamie Ball - Dumb Loop (Original Mix)",
        track36 : "Player - Player Eighteen - 02 Player 018 B1 (Original Mix)",
        track37 : "Mr Peg - Beg Me (Original Mix)",
        track38 : "Patrick DSP - Dank Molly (Original Mix)",
        track39 : "Luis Ruiz & Andreas Florin - Conscience (Original Mix)",
        track4 : "Dave The Drummer & Chris Liberator - Underthreat (Patrick DSP Remix)",
        track40 : "Michael Burkat & Lars Klein - Go On A Knees And Suck Me Denise (Original Mix)",
        track41 : "Ollie Linear - The Off Switch (OB1 Remix)",
        track42 : "Broken Rules - Simplified (Original Mix)",
        track43 : "DJ MinuPren - Was Aus Der Frau... (Original Mix)",
        track44 : "Broken Rules - Floor Plans (Original Mix)",
        track45 : "Jamie Ball - Killafornia (Original Mix)",
        track5 : "DJ Dro San - O Niga vs a Niga (Original Mix)",
        track6 : "Slut Peddler's - The Gimp - (Original Mix)",
        track7 : "Ryuji Takeuchi - Kei-Han-Shin (Original Mix)",
        track8 : "Lars Klein - Fighting With The Fire (Original Mix)",
        track9 : "Player - Infamous Player Classics Vol I - 01 Player 023 A1",
        tracksBy : "Jamie Ball, Patrick DSP, Wetworks, Broken Rules, DJ Ogi, Gary The Apprentice & Audioklinik"
    },
    {
        artistName : "Mallory",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast24.jpg?alt=media&token=f8e092ce-6d22-4981-b8c7-555a781a4706",
        duration : "1hr",
        id : 24,
        playerSrc: 'https://app.hearthis.at/embed/4447323/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "6 March 2020",
        releaseInfoP1 : "I'm very pleased to welcome Mallory to the GTA Digital Podcast Series, with an absolutely outstanding mix, as heard in this months installment of GTA Digital Presents.",
        releaseInfoP2 : "This is up there with one of my favourite mixes, some seriously decent techno, mixed perfectly.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast24.jpg?alt=media&token=47a3a025-9860-4cef-bdde-46bf2abdfbe1",
        title : "GTA Digital Podcast #24",
        track1 : "Inox Traxx - Sound Effects (Original Mix)",
        track10 : "Dave Mono - There was danger (Original Mix)",
        track11 : "6SISS - Dont (Original Mix)",
        track12 : "Jerome Hill - Insomnia (Original Mix)",
        track13 : "Cadans - Hose (Original Mix",
        track14 : "SHXCXCHCXSH - GBG (Original Mix)",
        track15 : "OverworX - You better know (Original Mix)",
        track16 : "Joe Farr - Well tempered (Original Mix)",
        track17 : "Ghost in the machine - Combo breaker (Original Mix)",
        track18 : "Ingen - Cow lip (Original Mix)",
        track19 : "Interferon - Fraud (Draugr Remix)",
        track2 : "Mad-Tek - When the wheels fall off (Nexus 23 remix)",
        track20 : "Ingen - The meat world matters (Original Mix)",
        track21 : "Ceili - Not a fear of it (Rommek's party line remix)",
        track22 : "Lag - Time, Blood and Ego (JoeFarr Remix)",
        track3 : "James Ruskin - Consumer Patterns (Original Mix)",
        track4 : "Karenn - Lemon Dribble (Original Mix)",
        track5 : "Cassegrain - First words (Original Mix)",
        track6 : "Giant Swan - YFPHNT (Original Mix)",
        track7 : "Ansome - Chocka Block (Original Mix)",
        track8 : "Makaton - Proximity (Original Mix)",
        track9 : "Joe Farr - Septum (Original Mix)",
        tracksBy : "James Ruskin, Karenn, Ansome, JorFarr, Cadans, Ingen & Lag"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast23.jpg?alt=media&token=2ff12b63-c636-4295-9c86-5a2627358e85",
        duration : "1hr",
        id : 23,
        playerSrc: 'https://app.hearthis.at/embed/4387668/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "4 February 2020",
        releaseInfoP1 : "GTA Digital Podcast Series is back. Expect an hour of slow, chunky, hypnotic techno, as heard in this months show GTA Digital Presents on Fnoob Techno Radio.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast23.jpg?alt=media&token=256b438b-e43c-4c48-a82e-5a8f190a56af",
        title : "GTA Digital Podcast #23",
        track1 : "Konnektin Dots (Original Mix) - Trackmaster Dre",
        track10 : "Armanis Ghost (Original Mix) - Absent",
        track11 : "Strong Interaction 2 (Original Mix) - Fanon Flowers",
        track12 : "Addictive Cycle (Original Mix) - Paul Mac",
        track13 : "From Within The Circle (Original Mix) - Alexander Kowalski",
        track14 : "Time is Now (Paul Mac Mix) - Lighter Thief",
        track15 : "Jaded (Original Mix) - Mark Broom",
        track16 : "I Told Em I Was from Detroit (Scan 7's Way of the 7 Remix) - DJ T-1000",
        track17 : "Night Shift (Original Mix) - YANT",
        track18 : "Far Right (Original Mix) - Forward Strategy Group",
        track19 : "Trap (Original Mix) - Vil",
        track2 : "That's My Sh*t (Original Mix) - Avision",
        track20 : "Rubble Trouble (Original Mix) - YANT",
        track21 : "Cause And Effect (Original Mix) - Lisa Oakes",
        track22 : "Headbutt (Original Mix) - YANT",
        track23 : "Rotten Nation (Original Mix) - Endlec",
        track3 : "Bite (Original Mix) - Cadans",
        track4 : "Any Day Now (Owslah & Goetz Remix) - Axkan",
        track5 : "Circuit Freaks (Original Mix) - Forward Strategy Group",
        track6 : "Trust In The True Spirit (Original Mix) - Alexander Kowalski",
        track7 : "Depot (Original Mix) - Chinanski",
        track8 : "Back to the Floor (Original Mix) - Paul Mac",
        track9 : "Twitched (Owslah & Goetz 'Northern' Mix) - Ken Ishii",
        tracksBy : "Trackmaster Dre, Avision, Paul Mac, Lighter Thief & Forward Strategy Group"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast22.jpg?alt=media&token=c5086a6c-ad89-45e7-a816-f8cf50c9c6ec",
        duration : "1hr",
        id : 22,
        playerSrc: 'https://app.hearthis.at/embed/4254357/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "10 January 2020",
        releaseInfoP1 : "GTA Digital Podcast Series is back with the first mix of 2020. This set also kicked off my first show on Fnoob Techno Radio for the year. I decided to kick things off with an almighty bang, and have put a set together with some older Hard Techno, Schranz and some hard banging Industrial Techno.",
        style : "Hard Techno, Schranz & Industrial",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast22.jpg?alt=media&token=00418d33-3d80-4044-89a0-2e095f66a73c",
        title : "GTA Digital Podcast #22",
        track1 : "Anthropophagus - Minimized (Original Mix)",
        track10 : "Alex Calver vs Traced & The Mexican - From The Darkside (Original Mix)",
        track11 : "Tobias Luke aka O.B.I - Seek and Destroy (Original Mix)",
        track12 : "Sven Wittekind - Superpimp (Original Mix)",
        track13 : "Robert Natus - Kidding? No! (Original Mix)",
        track14 : "Arkus P - My Real Love (Original Mix)",
        track15 : "Teknicity - Die (Original Mix)",
        track16 : "Arkus P - Crash (Original Mix)",
        track17 : "Wortex - Braindamage Scream (Original Mix)",
        track18 : "DJ Hamy - Evil Foreboding (Original Mix)",
        track19 : "Jason Little - Posed To Death (Original Mix)",
        track2 : "Boris S - Bondage (Original Mix)",
        track20 : "Rude Awakening vs DJ Amok - Electronic Rod (Waldhaus Remix)",
        track3 : "Kaoz - Bustenhalter (Original Mix)",
        track4 : "Matt M Maddox - Mighty Tool (Original Mix)",
        track5 : "Frank Kvitta & Robert Natus - First Contact (Original Mix)",
        track6 : "Sven Wittekind - Wrong Turn (Original Mix)",
        track7 : "Robert Natus & Arkus P - Hermoso (Hard Version)",
        track8 : "Alex Calver - Hostel (Original Mix)",
        track9 : "Alex TB - Bifurcacao (Original Mix)",
        tracksBy : "Boris S, Arkus P, Robert Natus, Alex Calver, Sven Wittekind & Matt M Maddox"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast21.jpg?alt=media&token=d41b5af1-e64d-4f12-b6de-50cee904add1",
        duration : "1hr",
        id : 21,
        playerSrc: 'https://app.hearthis.at/embed/4151212/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "11 December 2019",
        releaseInfoP1 : "This is the set that was used for my second GTA Digital Presents show on Fnoob Techno Radio, which aired on 10 December 2019.",
        releaseInfoP2 : "Expect an hour of straight, jacked up, wonky techno.",
        style : "Jackin/Wonky Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast21.jpg?alt=media&token=83e66112-2ff1-4356-bc05-6d0d853ad1f8",
        title : "GTA Digital Podcast #21",
        track1 : "Freaky Freaky (Original Mix) - DJ Ze MigL",
        track10 : "Dirty Jill - (Original Mix) - The Groove Asylum",
        track11 : "Neuroinus Fuckeduptedios (Original Mix) - DJ Mem",
        track12 : "Like It Never Happened (Original Mix) - Paul Birken",
        track13 : "Somewhere Within (Original Mix) - Justin Berkovi",
        track14 : "Finnish Deception (Original Mix) - Neil Landstrumm",
        track15 : "Textual Assault (Original Mix) - Mark Hawkins",
        track16 : "Let's Do It (Original Mix) - DJ Mem",
        track17 : "Custard Traxx (Original Mix) - Neil Landstrumm",
        track18 : "Drop Out (Original Mix) - Mark Hawkins",
        track19 : "Old It (Original Mix) - DJ Mem",
        track2 : "Carocha vs Carocho (Original Mix) - DJ Dro San",
        track20 : "Bump & Bang (Original Mix) - DJ Bam Bam",
        track21 : "Jackin - (Original Mix) - Space DJz",
        track3 : "Bob Barker's House (Original Mix) - Paul Birken",
        track4 : "Forget Your Reflection (Original Mix) - Justin Berkovi",
        track5 : "The Building Is On Fire (Original Mix) - DJ Ze MigL",
        track6 : "O Niga vs a Niga (Original Mix) - DJ Dro San",
        track7 : "The Family (Mark Hawkins Remix) - DJ Rush",
        track8 : "Hard Music Beat (Original Mix) - Ruben A",
        track9 : "You Really Would? (Original Mix) - Ruben A",
        tracksBy : "DJ Ze MigL, DJ Dro San, DJ Bam Bam, DJ Rush, Ruben A & Neil Landstrumm"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast20.jpg?alt=media&token=2f728fc4-ddca-49ff-8881-83a734163f52",
        duration : "1hr",
        id : 20,
        playerSrc: 'https://app.hearthis.at/embed/4006391/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "14 November 2019",
        releaseInfoP1 : "I'm very excited to present the 20th podcast in the GTA Digital Podcast Series, an hour of techno, performed live by myself, Gary The Apprentice. This is a massive achievement for me, having finally created and performed my very first live set just last month.",
        releaseInfoP2 : "This set contains only my own music, broken apart and reconstructed live using Ableton, a Novation Launchpad and Launchcontrol XL.",
        releaseInfoP3 : "This is a studio recording, with a couple of additional tracks added in which I did not include when performing this last month.",
        releaseInfoP4 : "This also marks the launch of my own show on Fnoob Techno Radio GTA Digital Presents. It's been an awesome year for me music wise, landing a residency for an awesome techno event based in Fife, Scotland called The Lick, which has been absolutely banging, building and performing my very first live set and getting my own show on Fnoob. Thanks to everyone who has supported my music!",
        style : "Techno/Hard Techno - Live PA",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast20.jpg?alt=media&token=ce2f1ead-e2b5-4355-a476-9919847622a3",
        title : "GTA Digital Podcast #20"
    },
    {
        artistName : "Lee Malice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast19.jpg?alt=media&token=3bbc570c-ddce-40b4-ae58-37cefb11e4cb",
        duration : "1hr",
        id : 19,
        playerSrc: 'https://app.hearthis.at/embed/3938425/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "27 October 2019",
        releaseInfoP1 : "Lee Malice is the man behind The Lick, a techno event based in Fife, Scotland. The Lick is hosted in secret locations, and this year threw 3 All Nighter events in one of the most industrial locations that a techno party could be held in. These events have played host to acts such as Jamie Ball, Neil Landstrum, Hostage, Msstec plus loads of acts from the local Scottish underground techno scene, inlcuding myself.",
        releaseInfoP2 : "The events that this boy has thrown have most definitely been the best I've played at since I started doing events in 2006. If you're in or around Central Scotland, keep an eye on The Lick and get yourself along to a future event.",
        releaseInfoP3 : "Not only does Lee know how to put on a banging party, but he can also smash it behind the decks. Enjoy the next hour of straight bangers!",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast19.jpg?alt=media&token=5741a44d-5d54-4415-a52a-38e133528724",
        title : "GTA Digital Podcast #19"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast18.jpg?alt=media&token=9d8469e7-4721-43a6-8fb9-a404a5a20794",
        duration : "1hr",
        id : 18,
        playerSrc: 'https://app.hearthis.at/embed/3098545/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "16 May 2019",
        releaseInfoP1 : "After an absolutely banging gig at The Lick All Nighter on 10 May 2019, I felt I should record the tracks that I played. It was quite possibly one of the most enjoyable gigs I've had, and also possibly one of the best events I've attended.",
        releaseInfoP2 : "For the 18th podcast, expect some straight up, bangin', and in the words of The Lick crew, BAWS OOT TECHNO.",
        style : "Hard Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast18.jpg?alt=media&token=776b9b3c-efff-43ef-9147-d5f895c52b9e",
        title : "GTA Digital Podcast #18",
        track1 : "Patrick DSP - Dank Molly (Original Mix)",
        track10 : "Lars Klein - Black Rain (Original Mix)",
        track11 : "Glenn Wilson & Mike Humphries - Shackled (Original Mix)",
        track12 : "Patrick DSP - Ballistic Measures (Original Mix)",
        track13 : "Patrick DSP - Did I Stu-Stu-Studah Motha Fucka (Original Mix)",
        track14 : "D.A.V.E. The Drummer & The Anxious - Hydraulix 37 B1 (Original Mix)",
        track15 : "Mike Humphries & Glenn Wilson - Submit (Original Mix)",
        track16 : "DJ Urban - Hydraulix 13.4 (Original Mix)",
        track17 : "Patrick DSP - Moscow Bound (Original Mix)",
        track18 : "Patrick DSP - Big It Ah (Original Mix)",
        track19 : "Patrick DSP - Scum Like You (Original Mix)",
        track2 : "British Murder Boys - Rule By Law (Original Mix)",
        track3 : "Rectum Rocker - Firm Hands (Original Mix)",
        track4 : "Mr Peg - Beg Me (Original Mix)",
        track5 : "Lars Klein - Sweat pt. 2 (Original Mix)",
        track6 : "D.A.V.E. The Drummer Vs The Anxious - Hydraulix 16 A (Original Mix)",
        track7 : "The Anxious - Stalker (Original Mix)",
        track8 : "Dave The Drummer & Chris Liberator - Underthreat (Patrick DSP Remix)",
        track9 : "Slut Peddler's - The Gimp (Original Mix)",
        tracksBy : "Patrick DSP, British Murder Boys, Lars Klein, Glenn Wilson & The Anxious"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast17.jpg?alt=media&token=d4241a38-c21b-41b9-8a94-adffbcbd46da",
        duration : "1hr",
        id : 17,
        playerSrc: 'https://app.hearthis.at/embed/2589521/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "27 November 2018",
        releaseInfoP1 : "This set was originally aired on the October installment of the Doppler Shift Show, on Fnoob Techno Radio, and received a very good response. As it is no longer available on the Doppler Shift Soundcloud, I thought I would release it as part of the GTA Digital Podcast Series.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast17.jpg?alt=media&token=23032076-26bf-4f9c-a8a0-5000395a62cb",
        title : "GTA Digital Podcast #17",
        track1 : "Insolate - Obscure Object Of Desire (JoeFarr Remix)",
        track10 : "Myler - Peeling Oranges with your Face (Original Mix",
        track11 : "Ike Dusk - Interference (Jamie Curnock Remix)",
        track12 : "Joe Farr - Hanger 1 (Original Mix)",
        track13 : "Myler - Death Panel Procession (Myler Remix)",
        track14 : "JoeFarr - Furrl (Original Mix)",
        track15 : "Myler - Mandem (Original Mix)",
        track16 : "X-303 - Abuso Psicologico (Original Mix)",
        track17 : "Thomas P Heckmann - The Return (Paul Birken Remix)",
        track18 : "Ossian - Shock & Awe (Original Mix)",
        track19 : "Sascha Muller - Schleichfahrt (Original Mix)",
        track2 : "Chinanski - Primary (Original Mix)",
        track3 : "Ike Dusk - Trust (Original Mix)",
        track4 : "Jamie Curnock - Jack Killed Jill (Original Mix)",
        track5 : "OB1 - Turbo Shandy (Original Mix)",
        track6 : "Alexander Kowalski - Rotary Deadlock (Original Mix)",
        track7 : "Jamie Curnock - Reasoning (Daryl Remix)",
        track8 : "Ansome & Ossian - Butch (Original Mix)",
        track9 : "Endlec - We Have Failed (Original Mix)",
        tracksBy : "JoeFarr, Myler, Ike Dusk, Ansome, Jamie Curnock & OB1"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast16.jpg?alt=media&token=50d1d4d1-498f-4961-b378-fa049d16d220",
        duration : "1hr",
        id : 16,
        playerSrc: 'https://app.hearthis.at/embed/1550035/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "18 September 2017",
        releaseInfoP1 : "Gary The Apprentice lays down an hour of some seriously banging techno. Gary starts off with a more hypnotic edge but quickly moves into straight bangers. Expect to be taken into full on audio assault territory in the second half of the mix!",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast16.jpg?alt=media&token=60676bb2-d0ba-44c4-925d-ca51d24861e4",
        title : "GTA Digital Podcast #16",
        track1 : "Sonar Falls (Original Mix) - Planetary Assault Systems",
        track10 : "002 (Original Mix) - Datasmok",
        track11 : "On your Life (Original Mix) - JoeFarr",
        track12 : "Einkolsch (Original Mix) - BR1002",
        track13 : "Knife (Original Mix) - Domenico Crisci",
        track14 : "Tormnt (Original Mix) - Jake Conlon",
        track15 : "Ektroma (Original Mix) - Jokasti & Nek",
        track16 : "India (Original Mix) - Dr Cyanide",
        track17 : "EX (Original Mix) - Domenico Crisci",
        track18 : "Funk You (Original Mix) - Jokasti & Nek",
        track19 : "Wine (C-System Remix) - Dr Cyanide, C-System",
        track2 : "Grke7 (Original Mix) - Jake Conlon",
        track20 : "To The Bone (Original Mix) - Perc",
        track21 : "Repeat Offender (Original Mix) - Paul Birken",
        track3 : "Uncertain Outcome (Original Mix) - Haeken",
        track4 : "Everything Is Drone (Original Mix) - Eloim",
        track5 : "To Wander on the Moon (Original Mix) - Under Black Helmet",
        track6 : "Road Maps (Original Mix) - Marco Effe",
        track7 : "Pehsc (Original Mix) - Jake Conlon",
        track8 : "Escape from Samsara (Original Mix) - Klankman",
        track9 : "Morchot (Original Mix) - Cortechs",
        tracksBy : "Jakasti & Nek, Jake Conlon, Paul Birken, Perc, Haeken & Under Black Helmet"
    },
    {
        artistName : "Horror Brawl",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast15.jpg?alt=media&token=83849e12-539d-4598-a700-0a5aed515c36",
        duration : "2hrs",
        id : 15,
        playerSrc: 'https://app.hearthis.at/embed/1347892/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "5 June 2017",
        releaseInfoP1 : "Expect two hours of some serious bangers!",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast15.jpg?alt=media&token=f2f7cf26-07dc-4388-a7c7-e41178bb8bf6",
        title : "GTA Digital Podcast #15",
        track1 : "Pessimist - Mist (Original Mix)",
        track10 : "Manse - Threadbare (Original Mix)",
        track11 : "Radial - War Scare (Original Mix)",
        track12 : "Gary The Apprentice - A Lesson Worth Learnin' (Original Mix)",
        track13 : "Mella Dee - Deep Soul (Original Mix)",
        track14 : "Mella Dee - Deep Soul (Endian Remix)",
        track15 : "Dustin Zahn - Forward Unto Dawn (Nikola Gala Remix)",
        track16 : "Interferon - Sterile Caste (Original Mix)",
        track17 : "Miclodiet - Z (Original Mix)",
        track18 : "Duo Alias - Lad Of Lesiure (Original Mix)",
        track19 : "Oleka - Korova Milk Bar (Original Mix)",
        track2 : "Cyd - 1b3113v31ny (Original Mix)",
        track20 : "Joyless - Dominion (Neil Landstrumm Remix)",
        track21 : "Gotshell - Physics (Scalameriya Remix)",
        track22 : "Ingen - Time Wounds All Heels (Original Mix)",
        track23 : "Kamikaze Space Programme - Type 2 (Original Mix)",
        track24 : "Headless Horseman - Sanctuary (Original Mix)",
        track25 : "DeFeKT - MG2 (Original Mix)",
        track26 : "Dark Sky - Kilter (Zenker Brothers Remix)",
        track27 : "Swarm Intelligence - Klang (Rory St John remix)",
        track28 : "Cassegrain - Skull Gun (Peder Mannerfelt Remix)",
        track29 : "Phase - Submerged Metropolitan (Original Mix)",
        track3 : "Ben Gibson - Siphon (Thomas Hessler Reconstruction)",
        track30 : "Ingen - Haste Makes Waste (Lag Remix)",
        track31 : "Green Velvet - Flash (Carl Craig's Paperclip People Mix)",
        track32 : "Jerome Hill - Drumwar (Original Mix)",
        track33 : "Unknown Artist - BTCHZ (Knight Rider)",
        track34 : "Tzusing - Face Of Electric (Original Mix)",
        track4 : "Donato Dozzy - The Night Rider (Original Mix)",
        track5 : "Jamaica Suk - Requiem (Original Mix)",
        track6 : "Pessimist - Inner Circle (Original Mix)",
        track7 : "Ben Pest - Crewcut (Original Mix)",
        track8 : "Gary Beck - Around You (Original Mix)",
        track9 : "Casper Hastings - Bubba Fat (Original Mix)",
        tracksBy : "Ben Pest, Ingen, Kamikaze Space Programme, Green Velvet & Jerome Hill"
    },
    {
        artistName : "Owen Ni",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast14.jpg?alt=media&token=a5c3801f-9c32-447b-9f36-412a18da4377",
        duration : "50mins",
        id : 14,
        playerSrc: 'https://app.hearthis.at/embed/1304041/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "1 May 2017",
        releaseInfoP1 : "Owen Ni is a musician, producer, DJ, and owner of the netlabel Run On Recordings. Starting in 2012, Owen has landed releases on well respected labels and has gained respect from countless artists in the game. His style drifts torwards a reminiscent sound of 90's Techno, normally labeled as Detroit Techno, and the lushness of Berlin based sub genre Dub Techno. Together, he uses these styles to create his own sound and style. Although you can generally expect Electronic music from Owen, his influences are vast. From Hip Hop to Classic Rock, Jazz to Film Scores, Owen finds listening to and appreciating different types of music as a way to learn and grow as an artist.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast14.jpg?alt=media&token=0b450298-40d5-41b1-a18e-b697a009368e",
        title : "GTA Digital Podcast #14",
        track1 : "Regreso (Original Mix) - The Thinker",
        track10 : "Whomp Rat (Original Mix) - DJ Shiva",
        track11 : "Tube (Will Azada Remix) - Angel Alanis",
        track12 : "All Together (Original Mix) - Whim-ee",
        track13 : "Robotic Security Lighting (Original Mix) - Simone Gatto",
        track14 : "The Walking (Original Mix) - Paul Birken",
        track15 : "Insanity (Original Mix) - Sinister Minister",
        track2 : "Shadows (Original Mix) - Ron S",
        track3 : "Dark Journey Inland (The Passenger's Oberacid Remix) - Spin Fidelity",
        track4 : "Speaker Freak (Original Mix) - Paul Birken",
        track5 : "Disturbed (Original Mix) - N/A",
        track6 : "No Sleep At All (Original Mix) - DJ DeClerk",
        track7 : "QSpace (Original Mix) - Shifty Science",
        track8 : "Whoja Vu (Original Mix) - Robert Dietz",
        track9 : "Voice Four (In My Head) (Original Mix) - Minder",
        tracksBy : "Angel Alanis, Paul Birken, DJ Shiva, Spin Fidelity & Shifty Science"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast13.jpg?alt=media&token=2be9b043-d9a3-45cd-9e04-4cbf9082f0b7",
        duration : "1hr 16mins",
        id : 13,
        playerSrc: 'https://app.hearthis.at/embed/1151199/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "24 December 2016",
        releaseInfoP1 : "For the last podcast of 2016, Gary The Apprentice takes us on a journey through some deep, hypnotic techno, moving into more solid, straight up sounds as the mix progresses. Expect tracks by the likes of Invite, Developer, Joe Farr, Bas Mooy and many more. See the full tracklist below for details.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast13.jpg?alt=media&token=19264e9e-1d96-401d-97c0-7b469d6e08f9",
        title : "GTA Digital Podcast #13",
        track1 : "Micro (Original Mix) - Invite",
        track10 : "Shot In The Dark (Original Mix) - Savas Pascalidis",
        track11 : "Lost (Original Mix) - Moving Thoughts",
        track12 : "Dr Fastofle (Original Mix) - Zadig",
        track13 : "Lnwsd 001 (Original Mix) - Backlogs",
        track14 : "Son of Sins (Original Mix) - Bas Mooy",
        track15 : "Frozen Room (Original Mix) - Charles Fenckler",
        track16 : "Machine Dust (Original Mix) - Johnny Island",
        track17 : "District 2 (909 Drums) (Original Mix) - Charles Fenckler",
        track18 : "Kaayman Regiment (Original Mix) - Bas Mooy",
        track19 : "Kontrola (Bas Mooy remix) - Lag",
        track2 : "The People From Mars Don't Want Us There (Original Mix) - Moving Thoughts",
        track20 : "Grid (Original Mix) - Mode Regressiøn",
        track21 : "Funnel Fiends (Original Mix) - Paul Birken",
        track22 : "K E P L E R (Original Mix) - H8802",
        track3 : "Saga IV (Original Mix) - Tensal",
        track4 : "Generator (Original Mix) - Samuel L Session",
        track5 : "Ascender Calling (Original Mix) - Developer",
        track6 : "Morning Lobotomy (Flug Remix) - KMYLE",
        track7 : "Sama Doma (Forward Strategy Group remix) - Lag",
        track8 : "John (Original Mix) - Joe Farr",
        track9 : "Spiral Form (Original Mix) - Developer",
        tracksBy : "Invite, Samuel Session, Developer, Lag, Paul Birken & H8802"
    },
    {
        artistName : "Deep Audio",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast12.jpg?alt=media&token=0a037bf3-256d-4a05-9290-d9f59d98cb81",
        duration : "1hr",
        id : 12,
        playerSrc: 'https://app.hearthis.at/embed/1107636/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "16 November 2016",
        releaseInfoP1 : "Deep Audio started mixing in 2015, playing many styles across the Techno spectrum. They have more recently began on the production side of things, and hope to have some music finished soon.",
        releaseInfoP2 : "For this mix Deep Audio begin by taking us on a nice journey through some more hypnotic sounds, leading on to some straight, solid banging techno.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast12.jpg?alt=media&token=ebbb9441-da12-4d4e-b081-7528f5d0bc60",
        title : "GTA Digital Podcast #12",
        track1 : "Old Machines (Original Mix) - Jay Lumen",
        track10 : "Protect the Prophecy (Original Mix) - Dax J",
        track11 : "Imperial Propaganda (Original Mix) - Dax J",
        track12 : "Pandrah (Original Mix) - Amotik",
        track13 : "Daydream (Original Mix) - I Hate Models",
        track14 : "Revolte of the Clowns (Sebastian Groth Remix) - Sebastian Groth, BMG",
        track2 : "Kawasaki (Original Mix - 2000 and One",
        track3 : "Control (Original Mix) - Shifted",
        track4 : "Alone in Time (Original Mix) - Phase",
        track5 : "Terah (Original Mix) - Amotik",
        track6 : "Mirror (Original Mix - Lewis Fautzi",
        track7 : "Closer to God (Original Mix) - Dax J",
        track8 : "Warp (Original Mix) - Dax J",
        track9 : "Solah (Original Mix) - Amotik",
        tracksBy : "Shifted, Dax J, Phase & 2000 and One"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast11.jpg?alt=media&token=8a3e3a53-e458-4d34-8e89-d258d52ce838",
        duration : "1hr 8mins",
        id : 11,
        playerSrc: 'https://app.hearthis.at/embed/1077433/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "22 October 2016",
        releaseInfoP1 : "Gary The Apprentice takes you on a nice journey through some deep, hypnotic sounds, with some straight up bangers thrown in for good measure.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast11.jpg?alt=media&token=c59a5c7e-4975-45d0-9b3f-fb8fb0ff9e8f",
        title : "GTA Digital Podcast #11",
        track1 : "Wire (Original Mix) - Psyk",
        track10 : "In Pure Form 12 (Original Mix) - Developer",
        track11 : "Origin (Original Mix) - Psyk",
        track12 : "Jamsession 002 (Original Mix) - Marco Faraone",
        track13 : "Interlock (Jonas Kopp Mix) - Savas Pascalidis",
        track14 : "OE02 (Original Mix) - NX1",
        track15 : "Master Jack (Original Mix) - Robert Hood",
        track16 : "Md 100 (Original Mix) - Mike Dehnert",
        track17 : "It's a Love Thing (Piano Invasion) - Head High",
        track18 : "Echo 8 (Original Mix) - Mike Dehnert",
        track19 : "In Pure Form 20 (Original Mix) - Developer",
        track2 : "Black Air (Regal Remix) - Marco Faraone, Regal",
        track20 : "Raw Intentions (Raffaele Attanasio vs X501 Version) - Manuel Di Martino",
        track3 : "Stigma (Original Mix) - Psyk",
        track4 : "Necronomicon (Vin Sol & Matrixxman Remix) - MATRiXXMAN",
        track5 : "Jamsession 001 (Original Mix) - Marco Faraone",
        track6 : "Vortekz (Original Mix) - Vril",
        track7 : "Star Base (Original Mix) - Mike Dehnert",
        track8 : "30303B (Shd Ã San Mix) - Wax",
        track9 : "Talatone (Original Mix) - Blawan",
        tracksBy : "Developer, Psyk, Matrixxman, Blawan & Robert Hood"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast10.jpg?alt=media&token=419dda48-9442-4128-92bd-f370542d59f2",
        duration : "1hr",
        id : 10,
        playerSrc: 'https://app.hearthis.at/embed/1029619/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "14 September 2016",
        releaseInfoP1 : "Gary The Apprentice is back for the 10th Podcast in our series.",
        releaseInfoP2 : "For this mix Gary has went through a selection of some old straight up, solid techno. Expect tracks from the likes of Surgeon, James Ruskin, Damon Wild, Joey Beltram and more. See track list below for more details.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast10.jpg?alt=media&token=30f792e7-f2e5-445c-abc7-54755822e7ef",
        title : "GTA Digital Podcast #10",
        track1 : "Apartment Zero (Original Mix) - Robert Hood",
        track10 : "Handiwork (Handiwork Cari Lekebusch Mix) - Steve Stoll",
        track11 : "Slim Sez (Original Mix) - Cari Lekebusch",
        track12 : "Number In Between (Original Mix) - Adam Beyer, Jesper Dahlback",
        track13 : "Purification (Original Mix) - Regis",
        track14 : "Version (Original Mix) - James Ruskin",
        track15 : "Surface (Original Mix) - Regis",
        track16 : "Life Disintegrating (Original Mix) - Pacou",
        track17 : "Your Green Eyes (Original Mix) - Chris McCormack",
        track18 : "Move (Original Mix) - Surgeon",
        track19 : "Events (Original Mix) - Element 3",
        track2 : "First (Original Mix) - Surgeon",
        track20 : "Detatched (Original Mix) - James Ruskin",
        track21 : "Compressed (Original Mix) - Chris McCormack",
        track3 : "Waveterm (Original Mix) - Damon Wild, Function",
        track4 : "Flight Decimator (Original Mix) - Chris McCormack",
        track5 : "Oval (Original Mix) - Joey Beltram",
        track6 : "Eight 3 (Original Mix) - James Ruskin",
        track7 : "Fuel (Original Mix) - Pacou",
        track8 : "Set Ups (Original Mix) - Joey Beltram",
        track9 : "Bang The Acid (Joey Beltram Remix) - Damon Wild, Tim Taylor",
        tracksBy : "Surgeon, Pacou, Jame Ruskin, Chris McCormack & Damon Wild"
    },
    {
        artistName : "LBM12",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast9.jpg?alt=media&token=2be7003e-ae32-4062-9c5a-70d0c52dfa4e",
        duration : "1hr 16mins",
        id : 9,
        playerSrc: 'https://app.hearthis.at/embed/988274/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "18 August 2016",
        releaseInfoP1 : "The GTA Digital Podcast is back with a really nice mix by Amsterdam based LBM12.",
        releaseInfoP2 : "LBM12 has put together a very nice four deck vinyl mix, expect a nice journey through some deep, solid, hypnotic Techno.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast9.jpg?alt=media&token=34fd8aa2-f732-425e-865a-4e0986387d7b",
        title : "GTA Digital Podcast #9"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast8.jpg?alt=media&token=f9a5cf5b-412e-451e-ac48-d88d380a280e",
        duration : "1hr 13mins",
        id : 8,
        playerSrc: 'https://app.hearthis.at/embed/639134/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "8 January 2016",
        releaseInfoP1 : "For the first Podcast of 2016, Gary The Apprentice has dusted off some old vinyl. Expect 100% Jackin Techno.",
        style : "Jackin Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast8.jpg?alt=media&token=9e84953c-c031-4529-970b-ff1a358709ad",
        title : "GTA Digital Podcast #8",
        tracksBy : "Jamie Bissmire, Jack Nation, Kamikaze, Paul Langley & DJ Bam Bam"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast7.jpg?alt=media&token=6862eace-af5d-47ab-b3bb-c9ef83731404",
        duration : "2hr",
        id : 7,
        playerSrc: 'https://app.hearthis.at/embed/611284/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "22 December 2015",
        releaseInfoP1 : "Onto the final podcast of 2015, Gary The Apprentice has put together a nice 2 hour mix for your listening pleasure. Expect a diverse blend of Techno.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast7.jpg?alt=media&token=cf233b89-4422-472b-aec1-ec98d1aa47d4",
        title : "GTA Digital Podcast #7",
        track1 : "Sweet Decay (Original Mix) - Brendon Moeller",
        track10 : "Indictment (Original Mix) - Israel Vines",
        track11 : "Lux (Antigone Remix) - Stephen Brown",
        track12 : "Truant (Original Mix) - Alan Fitzpatrick",
        track13 : "No Stress (Original Mix) - Jonas Kopp",
        track14 : "Black Russian (Original Mix) - DVS1",
        track15 : "Metropolis How? (James Ruskin Remix) - Little Nobody",
        track16 : "Minimalism (DVS1 Remix) - Terrence Dixon",
        track17 : "In Their Steps (Original Mix) - Birth Of Frequency",
        track18 : "2 O'Clock Wake Up (Original Mix) - Valmay",
        track19 : "Walfisch (Original Mix) - Roman Poncet",
        track2 : "Clone (Original Mix) - Ross Evans",
        track20 : "All Day (Robert Hood Remix) - Gingy, Bordello",
        track21 : "Aurelon 10 (Original Mix) - Vince Watson",
        track22 : "Never Grow Old (Re-Plant) - Floorplan",
        track23 : "Minor A 10 (Original Mix) - Valmay",
        track24 : "Blade Runner (Zadig Remix) - Woo York",
        track25 : "Enter (Original Mix) - Antigone",
        track26 : "Bisonspoor (Original Mix) - Invite",
        track27 : "Ripple Effect (Original Mix) - Ross Alexander",
        track28 : "A Better Way Of Living (Original Mix) - Sigha",
        track29 : "Spider (Original Mix) - Surgeon",
        track3 : "Its All in Your Mind (Lo Shea Remix) - Dan Curtin",
        track30 : "Zilla (Original Mix) - Surgeon",
        track31 : "Afterglow (Original Mix) - Roman Poncet",
        track32 : "Tsiu (J. Tijn Remix) - Boner M",
        track33 : "Straight At Me (Original Mix) - Kitkatone",
        track34 : "Space (DVS1 Remix) - Gennaro Mastrantonio, Billy Johnston",
        track35 : "Flyby/Falling (Enhanced Version) - Phase",
        track36 : "Hank (Original Mix) - Jonas Kopp",
        track4 : "Dazzid (Original Mix) - Franklin De Costa",
        track5 : "Glance (Original Mix) - Dan Curtin",
        track6 : "One Evening At Mrs Applebee's (Purveyors Of Fine Funk Mix) - Dan Curtin",
        track7 : "Silenth Noises (Robert Hood Remix) - Roel Salemink",
        track8 : "Spectrafuck (James Ruskin Remix) - Sawlin",
        track9 : "Self Portrait (I:Cube Remix) - Terrence Dixon",
        tracksBy : "Brendon Moeller, Dan Curtin, Terrence Dixon, Stephen Brown, DVS1 & Vince Watson"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast6.jpg?alt=media&token=2f519439-cdfc-4917-9c9d-0afc799149d4",
        duration : "1hr 22mins",
        id : 6,
        playerSrc: 'https://app.hearthis.at/embed/533806/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "7 November 2015",
        releaseInfoP1 : "After a bit of a break due to having a busy few months, Gary The Apprentice is back with a new mix for the Podcast Series. Expect a nice journey through all things deep, chunky & hypnotic Techno, with a few bangers thrown in for good measure.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast6.jpg?alt=media&token=53b92ed6-e52d-4c23-975a-1f9f4bedf9cd",
        title : "GTA Digital Podcast #6",
        track1 : "Indunk (Ryan James Ford Remix) - Shako",
        track10 : "Fallen Night Renew (Original Mix) - O/V/R",
        track11 : "Is It Skinny (Original Mix) - Truncate",
        track12 : "Design (Original Mix) - Birth Of Frequency",
        track13 : "Distance (Original Mix) - Jonas Kopp",
        track14 : "Freefall (Original Mix) - Yan Cook",
        track15 : "Patient Zero (Function Remix) - Rødhåd",
        track16 : "Reeds Lake (Jonas Kopp Remix) - Myles Serge",
        track17 : "The Beginning of Something (Original Mix) - Birth Of Frequency",
        track18 : "Hope (Original Mix) - Rødhåd",
        track19 : "Random Attractions (Original Mix) - Developer",
        track2 : "Mentality (Original Mix) - Emmanuel",
        track20 : "Contortions (Jonas Kopp Remix) - Simon Haydo",
        track21 : "Debt Free Mann (Original Mix) - Cleric",
        track22 : "Rotula (Original Mix) - Oscar Mulero",
        track23 : "Unforeseen (Steve Bicknell Remix) - Terence Fixmer",
        track24 : "Penrose (Original Mix) - Cleric",
        track25 : "Liebcraft (Original Mix) - Rebekah",
        track3 : "Surplus (Original Mix) - Skudge",
        track4 : "Untitled B2 (Original Mix) - Shifted",
        track5 : "Interior (Original Mix) - O/V/R",
        track6 : "No Time Soon (Original Mix) - Mark Broom & James Ruskin",
        track7 : "Void (Truncate Remix) - Woo York",
        track8 : "Stp (Original Mix) - Jonas Kopp",
        track9 : "Outer Space Division (Original Mix) - Random Audio",
        tracksBy : "Skudge, Mark Broom, James Ruskin, Jonas Kopp, Truncate & Birth of Frequency"
    },
    {
        artistName : "Nizzy",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast5.jpg?alt=media&token=0ea92b6b-c1ef-4e5c-9c9c-c21c6e65a82e",
        duration : "1hr",
        id : 5,
        playerSrc: 'https://app.hearthis.at/embed/208564/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "2 May 2015",
        releaseInfoP1 : "GTA Digital Podcast is back, with a seriously banging mix from London based DJ/Producer Nizzy. We're really please to have Nizzy on board and love what he has put together for the 5th podcast in our series. Check this out if you like raw, banging Techno!",
        style : "Dark Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast5.jpg?alt=media&token=83068103-010e-4213-a8df-0b7a6a55e4ce",
        title : "GTA Digital Podcast #5",
        tracksBy : "Artificial Intelligence, I.M.D, Liquid Space, Poshout, Straftanz"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast4.jpg?alt=media&token=54a595d0-aa79-4054-95c8-f3f3d9f285bf",
        duration : "1hr",
        id : 4,
        playerSrc: 'https://app.hearthis.at/embed/32030/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "29 April 2014",
        releaseInfoP1 : "For the forth installment of the GTA Digital Podcast Series, label boss Gary The Apprentice is back with another mix. For this Podcast he has put together an hour of some nice hypnotic, solid, straight up techno, with a couple of pounders thrown in for good measure.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast4.jpg?alt=media&token=b211c4ec-4be9-4eee-8fc8-98372f8895e1",
        title : "GTA Digital Podcast #4",
        track1 : "Exium - Aces High (Original Mix)",
        track10 : "James Ruskin - Slit (Original Mix)",
        track11 : "Developer - Alone (Original Mix)",
        track12 : "Developer - Extension (Original Mix)",
        track13 : "James Ruskin, Mark Broom - D.O.D (Original Mix)",
        track14 : "The Fear Ratio - Dirty Paws (Original Mix)",
        track15 : "Israel Toledo - Magtis (Andrei Morant Remix)",
        track16 : "Damon Wild, Voltage 9 - Candema (Original Mix)",
        track17 : "Chris Colburn - Ckmd (Original Mix)",
        track18 : "Rebekah - Suicide Mind (Original Mix)",
        track19 : "Rebekah - Self Destruct (Original Mix)",
        track2 : "Ctrls - Program (Original Mix)",
        track3 : "Paul Boex - Bruma (Inigo Kennedy Remix)",
        track4 : "Developer - Sequencia 88 (Original Mix)",
        track5 : "Rebekah - Rouge Noir (Original Mix)",
        track6 : "Developer - Heated (Original Mix)",
        track7 : "D-Side - 610 A (MTD Rework)",
        track8 : "Ronan Portela, Ariel Rodz - Among Noise (Jonas Kopp Remix)",
        track9 : "Ctrls - Displacer (Original Mix)",
        tracksBy : "Paul Boex, Rebekah, Ctrls, Developer & The Fear Ratio"
    },
    {
        artistName : "Krowne",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast3.jpg?alt=media&token=745a190b-d167-4148-a4c5-4a1fcfe87d9d",
        duration : "1hr 12mins",
        id : 3,
        playerSrc: 'https://app.hearthis.at/embed/30208/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "20 March 2014",
        releaseInfoP1 : "For the third installment of the GTA Digital Podcast, we welcome Krowne. Krowne is a UK based DJ/Producer, and has been producing for about 8 years. He is more well known for his HipHop & Electronica influenced Bass Music. He has many releases under his belt, including his Open Box EP which was released for free through GTA Digital.",
        releaseInfoP2 : "For this Podcast, you can expect a nice journey through deep, tribal and straight up Techno.",
        style : "Deep Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast3.jpg?alt=media&token=13e6ff55-48ef-4e29-a9c2-e585dc4ebc0a",
        title : "GTA Digital Podcast #3",
        track1 : "Florian Meindl - The Theorem (Original Mix)",
        track10 : "Drumcomplex & Roel Salemink - Launch (Tomy DeClerque Remix)",
        track11 : "Gabeen - Artificial Light (Original Mix)",
        track12 : "Johann Smog, Luis MF - What The Wind (Skober Remix)",
        track13 : "Martyn Hare - Broken (Albert Kraner Remix)",
        track14 : "Secret Cinema - Bam Bam (Sasha Carassi Remix)",
        track15 : "Smilla - Being And Becoming (Original Mix)",
        track16 : "Spiriakos - Cosmic Trigger (Original Mix)",
        track17 : "Subwave - Naked Lunch (Original Mix)",
        track18 : "Sven Wittekind - Friday 13th (Original Mix)",
        track19 : "The Advent - Veron (Original Mix)",
        track2: "Andrea Lenci - Oss77 (Original Mix)",
        track20 : "The Japanese Popstars , Green Velvet - Matter Of Time (Original Mix)",
        track21 : "The Junkies - Dreams (Timmo Remix)",
        track22 : "X-Press 2 , Sonny Wharton - Watching Octavia (Original Mix)",
        track3 : "Abstract World - Aim 1.1 (Original Mix)",
        track4 : "Angel Alanis - Do You Like The Way You Feel When You Shake (A Paul Remix)",
        track5 : "AnGy KoRe - Milf Please (Original Mix)",
        track6 : "Mark Meino - DeadCity (Original Mix)",
        track7 : "Dennis Bunas - Cheepouraw (Original Mix)",
        track8 : "DJ Preach - Dunia (Original Mix)",
        track9 : "Dolby D feat. MicRoCheep - Prudence (Original Mix)",
        tracksBy : "AnGy KoRe, The Advent, Subwave, Sven Wittekind & DJ Preach"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast2.jpg?alt=media&token=8cc12146-9bdd-49f9-aed5-a015715888f7",
        duration : "1hr",
        id : 2,
        playerSrc: 'https://app.hearthis.at/embed/19910/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "28 February 2014",
        releaseInfoP1 : "The second installment in our GTA Digital Podcast series. GTA Digital boss, Gary The Apprentice, has put together another hour mix, this time round with all of his own tracks, which have been released, for free, on the label.",
        style : "Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast2.jpg?alt=media&token=f65c3689-5f8e-4138-919e-d8dcc7b91ab4",
        title : "GTA Digital Podcast #2",
        track1 : "Gary The Apprentice - Chapter 1",
        track10 : "Gary The Apprentice - Mechanical Lifeforms 3.1",
        track11 : "Gary The Apprentice - Chapter 2",
        track12 : "Gary The Apprentice - Mechanical Lifeforms 1.1",
        track13 : "Gary The Apprentice - Hydro74",
        track14 : "Gary The Apprentice - Organised Kaos",
        track15 : "Gary The Apprentice - Sophisticated Mayhem",
        track16 : "Gary The Apprentice - Systematic Anarchy",
        track17 : "Gary The Apprentice - Mind Warp",
        track18 : "Gary The Apprentice - Mind Modulation",
        track19 : "Gary The Apprentice - The Wake Up Call",
        track2 : "Gary The Apprentice - Ping",
        track20 : "Gary The Apprentice - Time To Wake Up",
        track21 : "Gary The Apprentice - Wide Awake",
        track3 : "Gary The Apprentice - A Lesson Worth Learnin'",
        track4 : "Gary The Apprentice - The Journey",
        track5 : "Gary The Apprentice - Timespace",
        track6 : "Gary The Apprentice - Zev",
        track7 : "Gary The Apprentice - Chapter 4",
        track8 : "Gary The Apprentice - Spacetime",
        track9 : "Gary The Apprentice - Chapter 3",
        tracksBy : "All tracks written and produced by Gary The Apprentice"
    },
    {
        artistName : "Gary The Apprentice",
        artwork : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcover-images%2Fpodcasts%2Fpodcast1.jpg?alt=media&token=c037931c-916b-4d3d-83fa-36832dba7586",
        duration : "1hr",
        id : 1,
        playerSrc: 'https://app.hearthis.at/embed/19909/transparent/?hcolor=0193b7&color=c9c9c9&style=1&block_size=2&block_space=1&background=0&waveform=0&cover=1&autoplay=0&css=',
        releaseDate : "8 August 2014",
        releaseInfoP1 : "The first installment in our Podcast series. For the first ever Podcast, GTA Digital boss Gary The Apprentice, has put together a solid mix of tough funk, bangin' jackin and industrial techno. One for the fans of the harder styles in Techno!",
        style : "Hard Groove/Jackin Techno",
        thumbnailUrl : "https://firebasestorage.googleapis.com/v0/b/gta-digital-web-app.appspot.com/o/main-content%2Fcard-images%2Fpodcast%2Fpodcast1.jpg?alt=media&token=b1e50dde-b95e-42b4-abce-b0b3ad307bfd",
        title : "GTA Digital Podcast #1",
        track1 : "Ben Sims - Straight from Bolivia (Original Mix)",
        track10 : "Cari Lekebusch - Filterfitta (Original Mix)",
        track11 : "Mark Broom - The Jacking Zone (Original Mix)",
        track12 : "DJ Urban - Fuckin' Beat (Original Mix)",
        track13 : "DJ Bam Bam - Turn Da Bass Up (Original Mix)",
        track14 : "DJ Bam Bam featuring Alex Peace - Bam's Workout (Original Mix)",
        track15 : "Ruben A - You Really Would? (Original Mix)",
        track16 : "DJ Mem - Old It (Original Mix)",
        track17 : "DJ Panik - Bangers (Original Mix)",
        track18 : "DJ Bam Bam - B2K [Buda 2000] (Original mix)",
        track19 : "Manone - She Tied Me Up (Original Mix)",
        track2 : "Par Grindvik, Billie (SE) - Hold, Doubt, Back (Original Mix)",
        track20 : "DJ MinuPren - Beat Riddle Box (Original Mix)",
        track21 : "The Jack Foundation - Straight Jackit (Original Mix)",
        track22 : "DJ MinuPren - Was Aus Der Frau...",
        track23 : "Broken Rules = Simplified (Original Mix)",
        track24 : "Sandy Warez - This Is... (Fucking Kicking Mix)",
        track3 : "Lighter Thief - Like Dat (Original Mix)",
        track4 : "Mark Broom - Redial (Original Mix)",
        track5 : "Ben Sims - New Blood (Original Mix)",
        track6 : "James Ruskin, Mark Broom - Pigeon (Original Mix)",
        track7 : "Mark Broom - Fever (Original Mix)",
        track8 : "Mike Dehnert - Blattwerk (Original Mix)",
        track9 : "Ben Sims - Slow Motion (Skudge Mix)",
        tracksBy : "Ben Sims, Mike Dehnert, Mark Broom, DJ Bam Bam, Minupren & Broken Rules"
    }
]