import { Injectable } from '@angular/core'
import { Subject } from 'rxjs'

@Injectable()
export class ReleaseService {
    getReleases() {
        let subject = new Subject()
        setTimeout(() => {subject.next(RELEASES); subject.complete(); }, 100)
        return subject
    }

    getRelease(id:number) {
        return RELEASES.find(release => release.id === id)
    }
}

const RELEASES = [

    /*{
        id: 20,
        title: 'Purist EP',
        artistName: 'Ungrateful Ambassador',
        catNo: '[GTA020]',
        imageUrl: './assets/images/card-images/release-artwork/gta020.jpg',
        artwork: './assets/images/artwork/releases/gta020.jpg',
        releaseUrl: 'https://gtadigital.bandcamp.com/album/gta019-unix-ep',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: '',
        releasePlayer: '<iframe class="bandcamp" style="width: 700px; height: 120px; border: 0px;" src="https://bandcamp.com/EmbeddedPlayer/album=2747614855/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/artwork=none/transparent=true/" seamless><a href="https://gtadigital.bandcamp.com/album/gta019-unix-ep">[GTA019] Unix EP by Gary The Apprentice</a></iframe>'    
    },
    {
        id: 19,
        title: 'Unix EP',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA019]',
        imageUrl: './assets/images/card-images/release-artwork/gta019.jpg',
        artwork: './assets/images/artwork/releases/gta019.jpg',
        releaseUrl: 'https://gtadigital.bandcamp.com/album/gta019-unix-ep',
        releaseInfoP1: 'Supported by: Perc, Patrick DSP, Wetworks, Dr Motte, Ian Void, Ike Dusk, Millhouse, Raymundo Rodriguez [Jaded / London Techno], Julez Wyl [Jaded], Clarkee [Area 51], DJ K.N (Mass United), Africa Islam, DJ Warp (Japan) / Takashi Watanabe, DJ Ze Mig L, Danny Slade [Zone Magazine / Herald Radio], Daz Furey, Drop-E, Fausto [Dance Valley], Gemma Furbank, Hidden Reflection, John Rowe [Hypnohouse Trax], Julian Rutherford [Technoscene], Kereni [Forte], Luca Agnelli, Luigi Madonna, Mark Neenan, Matteo (Different Grooves), Newks, Nori [Posivision], Ray Marshall, Rondell Adams, Verschwender, Wayne DJC [Beyond Control] Zuni [Tribal Waves] & John Warwick [Primate Recordings]',
        releaseInfoP2: 'Tracks 1, 2 & 3 written by Gary The Apprentice',
        releaseInfoP3: 'Track 4 written by Gary The Apprentice and DJ Ze MigL',
        releaseInfoP4: 'Mastered by Jon Doe CLSM Mastering',
        releaseInfoP5: '',
        releaseDate: '13 May 2019',
        releasePlayer: '<iframe class="bandcamp" style="width: 700px; height: 120px; border: 0px;" src="https://bandcamp.com/EmbeddedPlayer/album=2747614855/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/artwork=none/transparent=true/" seamless><a href="https://gtadigital.bandcamp.com/album/gta019-unix-ep">[GTA019] Unix EP by Gary The Apprentice</a></iframe>'
    },
    {
        id: 18,
        title: 'What Have We Become',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA018]',
        imageUrl: './assets/images/card-images/release-artwork/gta018.jpg',
        artwork: './assets/images/artwork/releases/gta018.jpg',
        releaseUrl: 'https://gtadigital.bandcamp.com/album/gta019-unix-ep',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: '',
        releasePlayer: '<iframe class="bandcamp" style="width: 700px; height: 120px; border: 0px;" src="https://bandcamp.com/EmbeddedPlayer/album=2762695312/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/artwork=none/transparent=true/" seamless><a href="https://gtadigital.bandcamp.com/album/gta018-what-have-we-become">[GTA018] What Have We Become by Gary The Apprentice</a></iframe>'
    },
    {
        id: 17,
        title: 'Longitudinal Axis EP',
        artistName: 'Twistedbrain74',
        catNo: '[GTA017]',
        imageUrl: './assets/images/card-images/release-artwork/gta017.jpg',
        artwork: './assets/images/artwork/releases/gta017.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 16,
        title: 'Of Little Significance',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA016]',
        imageUrl: './assets/images/card-images/release-artwork/gta016.jpg',
        artwork: './assets/images/artwork/releases/gta016.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 15,
        title: 'A New Dimension',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA015]',
        imageUrl: './assets/images/card-images/release-artwork/gta015.jpg',
        artwork: './assets/images/artwork/releases/gta015.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 14,
        title: 'Back In The Burgh EP',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA014]',
        imageUrl: './assets/images/card-images/release-artwork/gta014.jpg',
        artwork: './assets/images/artwork/releases/gta014.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 13,
        title: 'Mindfulness EP',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA013]',
        imageUrl: './assets/images/card-images/release-artwork/gta013.jpg',
        artwork: './assets/images/artwork/releases/gta013.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 12,
        title: 'Roffa EP',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA012]',
        imageUrl: './assets/images/card-images/release-artwork/gta012.jpg',
        artwork: './assets/images/artwork/releases/gta012.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 11,
        title: 'Abstrakt Riddims EP',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA011]',
        imageUrl: './assets/images/card-images/release-artwork/gta011.jpg',
        artwork: './assets/images/artwork/releases/gta011.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 10,
        title: 'The Next Chapter EP',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA010]',
        imageUrl: './assets/images/card-images/release-artwork/gta010.jpg',
        artwork: './assets/images/artwork/releases/gta010.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 9,
        title: 'Open Box EP',
        artistName: 'Krowne',
        catNo: '[GTA009]',
        imageUrl: './assets/images/card-images/release-artwork/gta009.jpg',
        artwork: './assets/images/artwork/releases/gta009.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 8,
        title: 'Mornaaan! EP',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA008]',
        imageUrl: './assets/images/card-images/release-artwork/gta008.jpg',
        artwork: './assets/images/artwork/releases/gta008.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 0o7,
        title: 'Mind Warp EP',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA007]',
        imageUrl: './assets/images/card-images/release-artwork/gta007.jpg',
        artwork: './assets/images/artwork/releases/gta007.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 0o6,
        title: 'Organised Kaos EP',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA006]',
        imageUrl: './assets/images/card-images/release-artwork/gta006.jpg',
        artwork: './assets/images/artwork/releases/gta006.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 0o5,
        title: 'Mechanical Lifeforms EP',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA005]',
        imageUrl: './assets/images/card-images/release-artwork/gta005.jpg',
        artwork: './assets/images/artwork/releases/gta005.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 0o4,
        title: 'The Dunny Collection',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA004]',
        imageUrl: './assets/images/card-images/release-artwork/gta004.jpg',
        artwork: './assets/images/artwork/releases/gta004.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 0o3,
        title: 'Timespace EP',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA003]',
        imageUrl: './assets/images/card-images/release-artwork/gta003.jpg',
        artwork: './assets/images/artwork/releases/gta003.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 0o2,
        title: 'The Brass Continent',
        artistName: 'Jamie Ball',
        catNo: '[GTA002]',
        imageUrl: './assets/images/card-images/release-artwork/gta002.jpg',
        artwork: './assets/images/artwork/releases/gta002.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },
    {
        id: 0o1,
        title: 'Recharged EP',
        artistName: 'Gary The Apprentice',
        catNo: '[GTA001]',
        imageUrl: './assets/images/card-images/release-artwork/gta001.jpg',
        artwork: './assets/images/artwork/releases/gta001.jpg',
        releaseUrl: '',
        releaseInfoP1: '',
        releaseInfoP2: '',
        releaseInfoP3: '',
        releaseInfoP4: '',
        releaseInfoP5: '',
        releaseDate: ''
    },*/
]